version: 0.0
os: linux
files:
  # Copy frontend files to the web directory
  - source: /frontend/
    destination: /var/www/healthcare-app/frontend

  # Copy backend files to the backend directory
  - source: /backend/
    destination: /opt/healthcare-app/backend

# Hooks for deployment lifecycle events
hooks:
  BeforeInstall:
    - location: scripts/stop-server.sh
      timeout: 180

  AfterInstall:
    - location: scripts/start-server.sh
      timeout: 180

  ApplicationStart:
    - location: scripts/start-application.sh
      timeout: 180
