version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r src/requirements.txt
  build:
    commands:
      - pytest tests/
  post_build:
    commands:
      - echo "Build completed successfully!"
      - aws deploy push --application-name HealthcareAppDeploy --description "Deploying Healthcare App"
artifacts:
  files:
    - src/*
