version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - echo "Build completed successfully."
artifacts:
  files:
    - "**/*"
